/* auto-generated by napi-rs — do not hand-edit */
/* eslint-disable */

export interface EngineConfig {
  /** "standard" | "concurrent" | "lockfree" | "adaptive" */
  variant?: string;
  /** Use the compressed Patricia trie for reads (default: true) */
  readCompressed?: boolean;
  /** Use the compressed Patricia trie for writes (default: false) */
  writeCompressed?: boolean;
  /** Enable the split-plane (Hybrid) architecture (default: false) */
  enableSplitPlane?: boolean;
}

export interface Metadata {
  /** Primary value string */
  value: string;
  /** Arbitrary key-value attributes */
  attributes: Record<string, string>;
}

export interface EngineStats {
  size: number;
  inserts: number;
  lookups: number;
  hits: number;
  misses: number;
  removals: number;
}

/**
 * High-performance IP radix-tree engine.
 *
 * @example
 * ```ts
 * import { RadixIP } from 'radixip';
 *
 * const engine = new RadixIP();
 * engine.insert('10.0.0.0/8', { value: 'allow', attributes: { asn: 'AS1234' } });
 *
 * const match = engine.lookup('10.1.2.3');
 * console.log(match?.value);  // "allow"
 * ```
 */
export declare class RadixIP {
  /** Create a new engine, optionally customised with an EngineConfig. */
  constructor(config?: EngineConfig | undefined | null);

  /** Insert a CIDR prefix with associated metadata. */
  insert(subnet: string, metadata: Metadata): void;

  /** Longest-prefix match. Returns `null` when no prefix covers the IP. */
  lookup(ip: string): Metadata | null;

  /** Remove a prefix. Returns `true` if the entry existed. */
  remove(subnet: string): boolean;

  /** Returns `true` if any stored prefix covers the IP. */
  contains(ip: string): boolean;

  /** Remove all entries. */
  clear(): void;

  /** Number of stored prefixes. */
  readonly size: number;

  /** Performance statistics. */
  stats(): EngineStats;
}

/** Library semantic version. */
export declare function version(): string;
