[package]
name = "radixip-bench"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
radixip-core = { path = "../../lib/rust" }
criterion = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }