// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: radixip.proto

package radixipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata stores payload string and optional attributes map for a prefix.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_radixip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Metadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Request to insert a subnet prefix into the trie.
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_radixip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{1}
}

func (x *InsertRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *InsertRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response for insert operation.
type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsNew         bool                   `protobuf:"varint,2,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_radixip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{2}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *InsertResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to lookup an IP address.
type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_radixip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{3}
}

func (x *LookupRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// Response for IP lookup.
type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_radixip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{4}
}

func (x *LookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request to remove a prefix.
type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_radixip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// Response for prefix removal.
type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_radixip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RemoveResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request to check if a prefix exists.
type ContainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsRequest) Reset() {
	*x = ContainsRequest{}
	mi := &file_radixip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsRequest) ProtoMessage() {}

func (x *ContainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsRequest.ProtoReflect.Descriptor instead.
func (*ContainsRequest) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{7}
}

func (x *ContainsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// Response for prefix existence check.
type ContainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contains      bool                   `protobuf:"varint,1,opt,name=contains,proto3" json:"contains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsResponse) Reset() {
	*x = ContainsResponse{}
	mi := &file_radixip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsResponse) ProtoMessage() {}

func (x *ContainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsResponse.ProtoReflect.Descriptor instead.
func (*ContainsResponse) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{8}
}

func (x *ContainsResponse) GetContains() bool {
	if x != nil {
		return x.Contains
	}
	return false
}

// Request to clear the radix tree.
type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_radixip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{9}
}

// Response for tree clear operation.
type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_radixip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{10}
}

func (x *ClearResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request for engine statistics.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_radixip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{11}
}

// Response containing engine statistics.
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserts       int64                  `protobuf:"varint,1,opt,name=inserts,proto3" json:"inserts,omitempty"`
	Lookups       int64                  `protobuf:"varint,2,opt,name=lookups,proto3" json:"lookups,omitempty"`
	Hits          int64                  `protobuf:"varint,3,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses        int64                  `protobuf:"varint,4,opt,name=misses,proto3" json:"misses,omitempty"`
	Removals      int64                  `protobuf:"varint,5,opt,name=removals,proto3" json:"removals,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_radixip_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{12}
}

func (x *StatsResponse) GetInserts() int64 {
	if x != nil {
		return x.Inserts
	}
	return 0
}

func (x *StatsResponse) GetLookups() int64 {
	if x != nil {
		return x.Lookups
	}
	return 0
}

func (x *StatsResponse) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *StatsResponse) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *StatsResponse) GetRemovals() int64 {
	if x != nil {
		return x.Removals
	}
	return 0
}

func (x *StatsResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Response for streamed batch insert.
type StreamInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount uint64                 `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInsertResponse) Reset() {
	*x = StreamInsertResponse{}
	mi := &file_radixip_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInsertResponse) ProtoMessage() {}

func (x *StreamInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radixip_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInsertResponse.ProtoReflect.Descriptor instead.
func (*StreamInsertResponse) Descriptor() ([]byte, []int) {
	return file_radixip_proto_rawDescGZIP(), []int{13}
}

func (x *StreamInsertResponse) GetInsertedCount() uint64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

var File_radixip_proto protoreflect.FileDescriptor

const file_radixip_proto_rawDesc = "" +
	"\n" +
	"\rradixip.proto\x12\n" +
	"radixip.v1\"\xa5\x01\n" +
	"\bMetadata\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12D\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2$.radixip.v1.Metadata.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\rInsertRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.radixip.v1.MetadataR\bmetadata\"f\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06is_new\x18\x02 \x01(\bR\x05isNew\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x1f\n" +
	"\rLookupRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"X\n" +
	"\x0eLookupResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.radixip.v1.MetadataR\bmetadata\"'\n" +
	"\rRemoveRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"X\n" +
	"\x0eRemoveResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.radixip.v1.MetadataR\bmetadata\")\n" +
	"\x0fContainsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\".\n" +
	"\x10ContainsResponse\x12\x1a\n" +
	"\bcontains\x18\x01 \x01(\bR\bcontains\"\x0e\n" +
	"\fClearRequest\")\n" +
	"\rClearResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0e\n" +
	"\fStatsRequest\"\x9f\x01\n" +
	"\rStatsResponse\x12\x18\n" +
	"\ainserts\x18\x01 \x01(\x03R\ainserts\x12\x18\n" +
	"\alookups\x18\x02 \x01(\x03R\alookups\x12\x12\n" +
	"\x04hits\x18\x03 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06misses\x18\x04 \x01(\x03R\x06misses\x12\x1a\n" +
	"\bremovals\x18\x05 \x01(\x03R\bremovals\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"=\n" +
	"\x14StreamInsertResponse\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x04R\rinsertedCount2\xe6\x03\n" +
	"\fRadixService\x12?\n" +
	"\x06Insert\x12\x19.radixip.v1.InsertRequest\x1a\x1a.radixip.v1.InsertResponse\x12?\n" +
	"\x06Lookup\x12\x19.radixip.v1.LookupRequest\x1a\x1a.radixip.v1.LookupResponse\x12?\n" +
	"\x06Remove\x12\x19.radixip.v1.RemoveRequest\x1a\x1a.radixip.v1.RemoveResponse\x12E\n" +
	"\bContains\x12\x1b.radixip.v1.ContainsRequest\x1a\x1c.radixip.v1.ContainsResponse\x12<\n" +
	"\x05Clear\x12\x18.radixip.v1.ClearRequest\x1a\x19.radixip.v1.ClearResponse\x12?\n" +
	"\bGetStats\x12\x18.radixip.v1.StatsRequest\x1a\x19.radixip.v1.StatsResponse\x12M\n" +
	"\fStreamInsert\x12\x19.radixip.v1.InsertRequest\x1a .radixip.v1.StreamInsertResponse(\x01B>Z<github.com/Mwangi-Derrick/radixip/proto/radixip/v1;radixipv1b\x06proto3"

var (
	file_radixip_proto_rawDescOnce sync.Once
	file_radixip_proto_rawDescData []byte
)

func file_radixip_proto_rawDescGZIP() []byte {
	file_radixip_proto_rawDescOnce.Do(func() {
		file_radixip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_radixip_proto_rawDesc), len(file_radixip_proto_rawDesc)))
	})
	return file_radixip_proto_rawDescData
}

var file_radixip_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_radixip_proto_goTypes = []any{
	(*Metadata)(nil),             // 0: radixip.v1.Metadata
	(*InsertRequest)(nil),        // 1: radixip.v1.InsertRequest
	(*InsertResponse)(nil),       // 2: radixip.v1.InsertResponse
	(*LookupRequest)(nil),        // 3: radixip.v1.LookupRequest
	(*LookupResponse)(nil),       // 4: radixip.v1.LookupResponse
	(*RemoveRequest)(nil),        // 5: radixip.v1.RemoveRequest
	(*RemoveResponse)(nil),       // 6: radixip.v1.RemoveResponse
	(*ContainsRequest)(nil),      // 7: radixip.v1.ContainsRequest
	(*ContainsResponse)(nil),     // 8: radixip.v1.ContainsResponse
	(*ClearRequest)(nil),         // 9: radixip.v1.ClearRequest
	(*ClearResponse)(nil),        // 10: radixip.v1.ClearResponse
	(*StatsRequest)(nil),         // 11: radixip.v1.StatsRequest
	(*StatsResponse)(nil),        // 12: radixip.v1.StatsResponse
	(*StreamInsertResponse)(nil), // 13: radixip.v1.StreamInsertResponse
	nil,                          // 14: radixip.v1.Metadata.AttributesEntry
}
var file_radixip_proto_depIdxs = []int32{
	14, // 0: radixip.v1.Metadata.attributes:type_name -> radixip.v1.Metadata.AttributesEntry
	0,  // 1: radixip.v1.InsertRequest.metadata:type_name -> radixip.v1.Metadata
	0,  // 2: radixip.v1.LookupResponse.metadata:type_name -> radixip.v1.Metadata
	0,  // 3: radixip.v1.RemoveResponse.metadata:type_name -> radixip.v1.Metadata
	1,  // 4: radixip.v1.RadixService.Insert:input_type -> radixip.v1.InsertRequest
	3,  // 5: radixip.v1.RadixService.Lookup:input_type -> radixip.v1.LookupRequest
	5,  // 6: radixip.v1.RadixService.Remove:input_type -> radixip.v1.RemoveRequest
	7,  // 7: radixip.v1.RadixService.Contains:input_type -> radixip.v1.ContainsRequest
	9,  // 8: radixip.v1.RadixService.Clear:input_type -> radixip.v1.ClearRequest
	11, // 9: radixip.v1.RadixService.GetStats:input_type -> radixip.v1.StatsRequest
	1,  // 10: radixip.v1.RadixService.StreamInsert:input_type -> radixip.v1.InsertRequest
	2,  // 11: radixip.v1.RadixService.Insert:output_type -> radixip.v1.InsertResponse
	4,  // 12: radixip.v1.RadixService.Lookup:output_type -> radixip.v1.LookupResponse
	6,  // 13: radixip.v1.RadixService.Remove:output_type -> radixip.v1.RemoveResponse
	8,  // 14: radixip.v1.RadixService.Contains:output_type -> radixip.v1.ContainsResponse
	10, // 15: radixip.v1.RadixService.Clear:output_type -> radixip.v1.ClearResponse
	12, // 16: radixip.v1.RadixService.GetStats:output_type -> radixip.v1.StatsResponse
	13, // 17: radixip.v1.RadixService.StreamInsert:output_type -> radixip.v1.StreamInsertResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_radixip_proto_init() }
func file_radixip_proto_init() {
	if File_radixip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_radixip_proto_rawDesc), len(file_radixip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_radixip_proto_goTypes,
		DependencyIndexes: file_radixip_proto_depIdxs,
		MessageInfos:      file_radixip_proto_msgTypes,
	}.Build()
	File_radixip_proto = out.File
	file_radixip_proto_goTypes = nil
	file_radixip_proto_depIdxs = nil
}
