[package]
name = "radixip-grpc-interceptor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
radixip-policy = { path = "../../policy" }
radixip-config = { path = "../../config" }
radixip_rs = { workspace = true }
tower = "0.5.3"
tonic = "0.14.6"
