[package]
name = "radixip-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
radixip-tower = { path = "../radixip-tower" }
radixip-policy = { path = "../../policy" }
radixip-config = { path = "../../config" }
radixip_rs = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
futures-util = { workspace = true }
tower = { workspace = true }
tower-service = "0.3.3"
tokio.workspace = true
