[package]
name = "radixip-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
radixip-tower = { path = "../radixip-tower" }
radixip-policy = { path = "../../policy" }
radixip-config = { path = "../../config" }
radixip_rs = { workspace = true }
tracing = { workspace = true }
axum = "0.8.9"
futures-util.workspace = true
tower = "0.5.3"
tower-service = "0.3.3"
tokio.workspace = true
