[package]
name = "kitchen-sink-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
radixip_rs = { path = "../../lib/rust/engine" }
radixip-config = { path = "../../lib/rust/config" }
radixip-policy = { path = "../../lib/rust/policy" }
radixip-axum = { path = "../../lib/rust/adapters/radixip-axum" }
radixip-actix = { path = "../../lib/rust/adapters/radixip-actix" }
radixip-grpc-interceptor = { path = "../../lib/rust/adapters/interceptor" }

tokio = { workspace = true }
axum = { workspace = true }
actix-web = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
http = { workspace = true }
